name: Publish Godot Image

on:
  push:
  pull_request:
  schedule:
    - cron: '30 5 * * *'

jobs:
  create_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - id: set-matrix
        run: |
          pip install beautifulsoup4 requests
          values=$(python ./download_all.py)
          echo ${values}
          echo "::set-output name=version_matrix::${values}"
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: create_matrix
    strategy:
      matrix:
        version: ${{ fromJson(needs.create_matrix.outputs.version_matrix) }}
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build engines
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: VERSION=${{ matrix.version }}
          no-cache: false
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/godot:${{ matrix.version }}
